project:
  type: website
  output-dir: docs

website:
  title: "marketing analytics"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: projects

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
